/**
 * profileSuggestions/courseSuggestions.ts
 *
 * Suggestion configuration keyed by CourseCategory.
 *
 * IMPORTANT:
 * - These are general interest/skill/activity IDEAS relevant to each course area.
 * - They are NOT official university requirements or guaranteed admission boosters.
 * - They are NEVER automatically added to DocumentData.
 * - Counsellors/students must explicitly confirm each suggestion before it enters the CV.
 */

import type { CourseCategory } from "../types";
import type { CourseSuggestionConfig } from "./profileSuggestions.types";

export const courseSuggestions: Record<CourseCategory, CourseSuggestionConfig> = {

  "Computer Science / IT": {
    hobbies: [
      { label: "Coding", priority: "high" },
      { label: "Chess", priority: "medium" },
      { label: "Robotics", priority: "medium" },
      { label: "Technology Reading", priority: "medium" },
      { label: "Problem-Solving Games", priority: "low" },
      { label: "Building Small Digital Projects", priority: "medium" },
      { label: "Game Development", priority: "low" },
      { label: "Open Source Exploration", priority: "low" },
    ],
    skills: [
      { label: "Python", priority: "high" },
      { label: "Problem Solving", priority: "high" },
      { label: "Logical Thinking", priority: "high" },
      { label: "Algorithmic Thinking", priority: "high" },
      { label: "Data Analysis", priority: "medium" },
      { label: "JavaScript", priority: "medium" },
      { label: "Git / Version Control", priority: "medium" },
      { label: "Team Collaboration", priority: "medium" },
      { label: "Linux", priority: "low" },
      { label: "Database Fundamentals", priority: "low" },
    ],
    activities: [
      { label: "Coding Projects", priority: "high" },
      { label: "Hackathons", priority: "high" },
      { label: "Coding Competitions", priority: "medium" },
      { label: "Robotics Club", priority: "medium" },
      { label: "Open Source Participation", priority: "medium" },
      { label: "Technology Workshops", priority: "low" },
      { label: "Online Coding Courses", priority: "low" },
    ],
    academicInterests: [
      { label: "Artificial Intelligence", priority: "high" },
      { label: "Machine Learning", priority: "high" },
      { label: "Data Science", priority: "high" },
      { label: "Software Engineering", priority: "high" },
      { label: "Cybersecurity", priority: "medium" },
      { label: "Algorithms", priority: "medium" },
      { label: "Cloud Computing", priority: "medium" },
      { label: "Computer Networks", priority: "low" },
      { label: "Emerging Technologies", priority: "low" },
    ],
  },

  "Engineering": {
    hobbies: [
      { label: "Robotics", priority: "high" },
      { label: "Electronics", priority: "high" },
      { label: "DIY Projects", priority: "medium" },
      { label: "Technical Reading", priority: "medium" },
      { label: "Model Building", priority: "medium" },
      { label: "Chess", priority: "low" },
      { label: "Science & Technology", priority: "medium" },
      { label: "Problem-Solving Activities", priority: "medium" },
    ],
    skills: [
      { label: "Technical Problem Solving", priority: "high" },
      { label: "Mathematics", priority: "high" },
      { label: "CAD", priority: "medium" },
      { label: "Data Analysis", priority: "medium" },
      { label: "Programming", priority: "medium" },
      { label: "Technical Drawing", priority: "medium" },
      { label: "MATLAB", priority: "medium" },
      { label: "Team Collaboration", priority: "medium" },
      { label: "Research", priority: "low" },
      { label: "Project Planning", priority: "low" },
    ],
    activities: [
      { label: "Robotics Projects", priority: "high" },
      { label: "Engineering Competitions", priority: "high" },
      { label: "Electronics Projects", priority: "medium" },
      { label: "CAD Projects", priority: "medium" },
      { label: "Science Exhibitions", priority: "medium" },
      { label: "Technical Workshops", priority: "low" },
      { label: "Prototype Development", priority: "low" },
    ],
    academicInterests: [
      { label: "Robotics", priority: "high" },
      { label: "Automation", priority: "high" },
      { label: "Electronics", priority: "medium" },
      { label: "Mechanical Systems", priority: "medium" },
      { label: "Renewable Energy", priority: "medium" },
      { label: "Embedded Systems", priority: "medium" },
      { label: "Sustainable Engineering", priority: "low" },
      { label: "Engineering Design", priority: "low" },
    ],
  },

  "Business / Management": {
    hobbies: [
      { label: "Business Reading", priority: "high" },
      { label: "Entrepreneurship", priority: "high" },
      { label: "Current Business Affairs", priority: "high" },
      { label: "Chess", priority: "low" },
      { label: "Public Speaking", priority: "medium" },
      { label: "Business Podcasts", priority: "medium" },
      { label: "Networking", priority: "medium" },
      { label: "Market Observation", priority: "medium" },
    ],
    skills: [
      { label: "Business Analysis", priority: "high" },
      { label: "Communication", priority: "high" },
      { label: "Team Collaboration", priority: "high" },
      { label: "Microsoft Excel", priority: "medium" },
      { label: "Presentation Skills", priority: "medium" },
      { label: "Market Research", priority: "medium" },
      { label: "Problem Solving", priority: "medium" },
      { label: "Data Interpretation", priority: "medium" },
      { label: "Project Management", priority: "low" },
      { label: "Financial Literacy", priority: "low" },
    ],
    activities: [
      { label: "Entrepreneurship Club", priority: "high" },
      { label: "Business Case Competitions", priority: "high" },
      { label: "Market Research Projects", priority: "medium" },
      { label: "Student Business Society", priority: "medium" },
      { label: "Event Management", priority: "medium" },
      { label: "Family Business Involvement", priority: "low" },
      { label: "Business Workshops", priority: "low" },
    ],
    academicInterests: [
      { label: "Strategic Management", priority: "high" },
      { label: "Entrepreneurship", priority: "high" },
      { label: "Marketing", priority: "medium" },
      { label: "Business Analytics", priority: "medium" },
      { label: "International Business", priority: "medium" },
      { label: "Digital Transformation", priority: "medium" },
      { label: "Operations Management", priority: "low" },
      { label: "Consumer Behaviour", priority: "low" },
    ],
  },

  "Economics / Finance": {
    hobbies: [
      { label: "Financial News", priority: "high" },
      { label: "Economics Reading", priority: "high" },
      { label: "Current Affairs", priority: "high" },
      { label: "Investment Education", priority: "medium" },
      { label: "Statistics", priority: "medium" },
      { label: "Chess", priority: "low" },
      { label: "Business Podcasts", priority: "low" },
    ],
    skills: [
      { label: "Financial Analysis", priority: "high" },
      { label: "Data Analysis", priority: "high" },
      { label: "Statistics", priority: "high" },
      { label: "Microsoft Excel", priority: "high" },
      { label: "Quantitative Reasoning", priority: "medium" },
      { label: "Economic Analysis", priority: "medium" },
      { label: "Research", priority: "medium" },
      { label: "Presentation Skills", priority: "low" },
    ],
    activities: [
      { label: "Finance Club", priority: "high" },
      { label: "Economics Society", priority: "high" },
      { label: "Investment Simulation", priority: "medium" },
      { label: "Research Projects", priority: "medium" },
      { label: "Case Competitions", priority: "medium" },
      { label: "Economics Workshops", priority: "low" },
      { label: "Financial Literacy Activities", priority: "low" },
    ],
    academicInterests: [
      { label: "Macroeconomics", priority: "high" },
      { label: "Financial Markets", priority: "high" },
      { label: "Microeconomics", priority: "medium" },
      { label: "Behavioural Economics", priority: "medium" },
      { label: "Investment Analysis", priority: "medium" },
      { label: "International Economics", priority: "medium" },
      { label: "Development Economics", priority: "low" },
      { label: "Econometrics", priority: "low" },
    ],
  },

  "Political Science / International Relations": {
    hobbies: [
      { label: "Current Affairs", priority: "high" },
      { label: "Political History", priority: "high" },
      { label: "Reading", priority: "high" },
      { label: "Debate", priority: "high" },
      { label: "International News", priority: "medium" },
      { label: "Public Policy", priority: "medium" },
      { label: "Writing", priority: "medium" },
    ],
    skills: [
      { label: "Academic Research", priority: "high" },
      { label: "Critical Thinking", priority: "high" },
      { label: "Analytical Writing", priority: "high" },
      { label: "Public Speaking", priority: "high" },
      { label: "Debate", priority: "medium" },
      { label: "Policy Analysis", priority: "medium" },
      { label: "Source Evaluation", priority: "medium" },
      { label: "Presentation Skills", priority: "low" },
    ],
    activities: [
      { label: "Model United Nations", priority: "high" },
      { label: "Debate Club", priority: "high" },
      { label: "Essay Competitions", priority: "medium" },
      { label: "Student Council", priority: "medium" },
      { label: "Policy Research", priority: "medium" },
      { label: "Community Projects", priority: "medium" },
      { label: "Youth Parliament", priority: "low" },
      { label: "Current-Affairs Groups", priority: "low" },
    ],
    academicInterests: [
      { label: "International Relations", priority: "high" },
      { label: "Public Policy", priority: "high" },
      { label: "Diplomacy", priority: "high" },
      { label: "Comparative Politics", priority: "medium" },
      { label: "Human Rights", priority: "medium" },
      { label: "Political Economy", priority: "medium" },
      { label: "International Security", priority: "medium" },
      { label: "Governance", priority: "low" },
    ],
  },

  "Social Sciences": {
    hobbies: [
      { label: "Reading", priority: "high" },
      { label: "Social Issues", priority: "high" },
      { label: "Current Affairs", priority: "high" },
      { label: "Community Activities", priority: "medium" },
      { label: "Writing", priority: "medium" },
      { label: "Cultural Studies", priority: "medium" },
      { label: "Documentary Films", priority: "low" },
    ],
    skills: [
      { label: "Research", priority: "high" },
      { label: "Critical Thinking", priority: "high" },
      { label: "Academic Writing", priority: "high" },
      { label: "Communication", priority: "medium" },
      { label: "Data Interpretation", priority: "medium" },
      { label: "Qualitative Analysis", priority: "medium" },
      { label: "Survey Design", priority: "low" },
      { label: "Presentation Skills", priority: "low" },
    ],
    activities: [
      { label: "Community Projects", priority: "high" },
      { label: "Volunteering", priority: "high" },
      { label: "Awareness Campaigns", priority: "medium" },
      { label: "Social Research", priority: "medium" },
      { label: "Student Societies", priority: "medium" },
      { label: "NGO Activities", priority: "medium" },
      { label: "Debate", priority: "low" },
      { label: "Survey Projects", priority: "low" },
    ],
    academicInterests: [
      { label: "Sociology", priority: "high" },
      { label: "Psychology", priority: "high" },
      { label: "Social Policy", priority: "medium" },
      { label: "Human Development", priority: "medium" },
      { label: "Cultural Studies", priority: "medium" },
      { label: "Community Development", priority: "medium" },
      { label: "Gender Studies", priority: "low" },
      { label: "Migration", priority: "low" },
    ],
  },

  "Arts / Media / Design": {
    hobbies: [
      { label: "Photography", priority: "high" },
      { label: "Video Editing", priority: "high" },
      { label: "Art", priority: "high" },
      { label: "Illustration", priority: "medium" },
      { label: "Creative Writing", priority: "medium" },
      { label: "Film", priority: "medium" },
      { label: "Cinematography", priority: "medium" },
      { label: "Music", priority: "low" },
      { label: "Design", priority: "medium" },
    ],
    skills: [
      { label: "Graphic Design", priority: "high" },
      { label: "Video Editing", priority: "high" },
      { label: "Visual Communication", priority: "high" },
      { label: "Photography", priority: "medium" },
      { label: "Adobe Creative Tools", priority: "medium" },
      { label: "Storytelling", priority: "medium" },
      { label: "Content Creation", priority: "medium" },
      { label: "Creative Thinking", priority: "medium" },
      { label: "Presentation", priority: "low" },
    ],
    activities: [
      { label: "Portfolio Projects", priority: "high" },
      { label: "Design Competitions", priority: "high" },
      { label: "Short Films", priority: "medium" },
      { label: "Photography Projects", priority: "medium" },
      { label: "Creative Clubs", priority: "medium" },
      { label: "Social Media Content", priority: "low" },
      { label: "College Media Team", priority: "low" },
      { label: "Art Exhibitions", priority: "low" },
    ],
    academicInterests: [
      { label: "Digital Media", priority: "high" },
      { label: "Visual Communication", priority: "high" },
      { label: "Graphic Design", priority: "high" },
      { label: "Film Studies", priority: "medium" },
      { label: "Photography", priority: "medium" },
      { label: "Animation", priority: "medium" },
      { label: "User Experience Design", priority: "medium" },
      { label: "Creative Direction", priority: "low" },
    ],
  },

  "Health / Life Sciences": {
    hobbies: [
      { label: "Science Reading", priority: "high" },
      { label: "Health & Wellness Reading", priority: "high" },
      { label: "Biology", priority: "high" },
      { label: "Fitness", priority: "medium" },
      { label: "Nutrition", priority: "medium" },
      { label: "Community Service", priority: "medium" },
      { label: "Environmental Activities", priority: "low" },
    ],
    skills: [
      { label: "Scientific Research", priority: "high" },
      { label: "Data Interpretation", priority: "high" },
      { label: "Academic Writing", priority: "medium" },
      { label: "Laboratory Skills", priority: "medium" },
      { label: "Communication", priority: "medium" },
      { label: "Observation", priority: "medium" },
      { label: "Research Methods", priority: "medium" },
      { label: "Team Collaboration", priority: "low" },
    ],
    activities: [
      { label: "Science Projects", priority: "high" },
      { label: "Biology Competitions", priority: "high" },
      { label: "Science Clubs", priority: "medium" },
      { label: "Health Awareness Activities", priority: "medium" },
      { label: "Laboratory Projects", priority: "medium" },
      { label: "Community Volunteering", priority: "medium" },
      { label: "First-Aid Training", priority: "low" },
      { label: "Health Workshops", priority: "low" },
    ],
    academicInterests: [
      { label: "Human Biology", priority: "high" },
      { label: "Biotechnology", priority: "high" },
      { label: "Genetics", priority: "high" },
      { label: "Public Health", priority: "medium" },
      { label: "Neuroscience", priority: "medium" },
      { label: "Biomedical Science", priority: "medium" },
      { label: "Nutrition", priority: "medium" },
      { label: "Healthcare Research", priority: "low" },
    ],
  },

  "Natural Sciences": {
    hobbies: [
      { label: "Science Reading", priority: "high" },
      { label: "Mathematics", priority: "high" },
      { label: "Astronomy", priority: "medium" },
      { label: "Nature", priority: "medium" },
      { label: "Environmental Activities", priority: "medium" },
      { label: "Scientific Documentaries", priority: "medium" },
      { label: "Experimentation", priority: "low" },
    ],
    skills: [
      { label: "Scientific Research", priority: "high" },
      { label: "Mathematics", priority: "high" },
      { label: "Data Analysis", priority: "high" },
      { label: "Critical Thinking", priority: "medium" },
      { label: "Laboratory Techniques", priority: "medium" },
      { label: "Academic Writing", priority: "medium" },
      { label: "Observation", priority: "medium" },
      { label: "Research Methods", priority: "low" },
    ],
    activities: [
      { label: "Science Fairs", priority: "high" },
      { label: "Olympiads", priority: "high" },
      { label: "Laboratory Projects", priority: "medium" },
      { label: "Research Projects", priority: "medium" },
      { label: "Science Clubs", priority: "medium" },
      { label: "Environmental Projects", priority: "low" },
      { label: "Academic Workshops", priority: "low" },
    ],
    academicInterests: [
      { label: "Physics", priority: "high" },
      { label: "Chemistry", priority: "high" },
      { label: "Biology", priority: "high" },
      { label: "Mathematics", priority: "high" },
      { label: "Environmental Science", priority: "medium" },
      { label: "Astronomy", priority: "medium" },
      { label: "Climate Science", priority: "medium" },
      { label: "Scientific Research", priority: "low" },
    ],
  },

  "Law": {
    hobbies: [
      { label: "Reading", priority: "high" },
      { label: "Current Affairs", priority: "high" },
      { label: "Debate", priority: "high" },
      { label: "Legal News", priority: "high" },
      { label: "History", priority: "medium" },
      { label: "Public Speaking", priority: "medium" },
      { label: "Writing", priority: "medium" },
    ],
    skills: [
      { label: "Legal Research", priority: "high" },
      { label: "Critical Thinking", priority: "high" },
      { label: "Analytical Writing", priority: "high" },
      { label: "Argumentation", priority: "high" },
      { label: "Public Speaking", priority: "medium" },
      { label: "Research", priority: "medium" },
      { label: "Communication", priority: "medium" },
      { label: "Source Evaluation", priority: "low" },
    ],
    activities: [
      { label: "Moot Court", priority: "high" },
      { label: "Debate", priority: "high" },
      { label: "Model United Nations", priority: "medium" },
      { label: "Essay Competitions", priority: "medium" },
      { label: "Law Society", priority: "medium" },
      { label: "Legal Awareness Activities", priority: "medium" },
      { label: "Community Service", priority: "low" },
      { label: "Research Projects", priority: "low" },
    ],
    academicInterests: [
      { label: "Constitutional Law", priority: "high" },
      { label: "International Law", priority: "high" },
      { label: "Human Rights", priority: "high" },
      { label: "Corporate Law", priority: "medium" },
      { label: "Criminal Law", priority: "medium" },
      { label: "Public Policy", priority: "medium" },
      { label: "Legal Theory", priority: "low" },
    ],
  },

  "Hospitality / Tourism": {
    hobbies: [
      { label: "Travel", priority: "high" },
      { label: "Cooking", priority: "high" },
      { label: "Cultural Exploration", priority: "high" },
      { label: "Photography", priority: "medium" },
      { label: "Event Planning", priority: "medium" },
      { label: "Food Culture", priority: "medium" },
      { label: "Languages", priority: "medium" },
    ],
    skills: [
      { label: "Communication", priority: "high" },
      { label: "Customer Service", priority: "high" },
      { label: "Cultural Awareness", priority: "high" },
      { label: "Organisation", priority: "medium" },
      { label: "Event Management", priority: "medium" },
      { label: "Teamwork", priority: "medium" },
      { label: "Problem Solving", priority: "medium" },
      { label: "Presentation", priority: "low" },
    ],
    activities: [
      { label: "Event Organisation", priority: "high" },
      { label: "Cultural Events", priority: "medium" },
      { label: "Hospitality Workshops", priority: "medium" },
      { label: "Tourism Projects", priority: "medium" },
      { label: "Community Activities", priority: "low" },
      { label: "Customer-Service Experience", priority: "low" },
      { label: "Travel Research", priority: "low" },
    ],
    academicInterests: [
      { label: "Hospitality Management", priority: "high" },
      { label: "Tourism Management", priority: "high" },
      { label: "Event Management", priority: "high" },
      { label: "Sustainable Tourism", priority: "medium" },
      { label: "Customer Experience", priority: "medium" },
      { label: "International Tourism", priority: "medium" },
      { label: "Food & Beverage Management", priority: "low" },
    ],
  },

  "Other": {
    hobbies: [
      { label: "Reading", priority: "medium" },
      { label: "Sports", priority: "low" },
      { label: "Volunteering", priority: "medium" },
      { label: "Photography", priority: "low" },
      { label: "Music", priority: "low" },
      { label: "Travel", priority: "low" },
      { label: "Creative Activities", priority: "low" },
      { label: "Community Activities", priority: "medium" },
    ],
    skills: [
      { label: "Communication", priority: "medium" },
      { label: "Teamwork", priority: "medium" },
      { label: "Research", priority: "medium" },
      { label: "Problem Solving", priority: "medium" },
      { label: "Presentation Skills", priority: "low" },
      { label: "Time Management", priority: "low" },
      { label: "Organisation", priority: "low" },
      { label: "Critical Thinking", priority: "medium" },
    ],
    activities: [
      { label: "Volunteering", priority: "medium" },
      { label: "Student Clubs", priority: "medium" },
      { label: "Personal Projects", priority: "medium" },
      { label: "Competitions", priority: "low" },
      { label: "Workshops", priority: "low" },
      { label: "Community Activities", priority: "low" },
      { label: "Online Courses", priority: "low" },
    ],
    academicInterests: [
      { label: "Independent Learning", priority: "medium" },
      { label: "Research", priority: "medium" },
      { label: "Interdisciplinary Studies", priority: "low" },
    ],
  },
};
